// Imports 
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// Import components 
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";



const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap", // Use 'swap' to avoid FOIT
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
